FROM nginx:latest

LABEL com.example.version="1.0.0"
LABEL com.example.release-date="30-09-2023"
LABEL com.example.production="True"
LABEL com.example.project="jogo-da-velha"

COPY . /usr/share/nginx/html/